## Computing a matrix inverse can be expensive. The following two functions work
## together to find and cache the inverse of a matrix so that the inverse only
## has to be computed once.

## Generates a special object that holds the matrix and can cache the inverse of
## the matrix. Assumes x is an invertible square matrix.

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y){
        x   <<- y
        inv <<- NULL
    }
    get <- function(){ x }
    setinverse <- function( i ){ inv <<- i }
    getinverse <- function(){ inv }
    list( set = set,
          get = get,
          setinverse = setinverse,
          getinverse = getinverse )
}


## cachceSolve takes a special matrix object generated by makeCacheMatrix and
## returns the inverse.

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    inv = x$getinverse()
    if( !is.null( inv ) ){ return(inv) }
    mat <- x$get()
    inv <- solve( mat, ... )
    x$setinverse( inv )
    inv
}
